### ISSUE TITLE
rename directories

### ISSUE THREAD

**Issue by mortonjt** [biocore/oecophylla#27]
The following directories need to be renamed
- [ ] `bin` -> `binning`
- [ ] `mash` -> `distance`
- [ ] `anvio` -> `visualization`
- [ ] `tax` -> `taxonomy`

**Comment by qiyunzhu** [comment]
tax -> taxonomy ?

**Comment by tanaes** [comment]
Talking with @sjanssen2, let's hold off on renaming these until he gets his PR in. 

Personally I think bin -> binning and tax -> taxonomy make sense, but mash -> distance seems too generalized to me.

**Comment by tanaes** [comment]
Fixed in #77
