### ISSUE TITLE
Allow install-derived paths to Snakemake resources

### ISSUE THREAD

**Issue by tanaes** [biocore/oecophylla#3]
Currently, the Snakefile include modules by importing them using a path to the `oecophylla` install that is hardcoded into the config.yaml file:

```python

snakefiles = os.path.join(config["software"]["snakemake_folder"],
                          "bin/snakefiles/")

include: snakefiles + "simplify_fasta.py"

include: snakefiles + "folders"
```

This should be handled by setup.py or similar.

**Comment by mortonjt** [comment]
Relevant to #24

**Comment by mortonjt** [comment]
Note that there is a `__file__` variable that keeps track of the path location of the given file, so this should be an easy replace

**Comment by tanaes** [comment]
This is actually not a problem.
