### ISSUE TITLE
make the installation more verbose

### ISSUE THREAD

**Issue by antgonza** [biocore/oecophylla#37]
the last step of the installation `find oecophylla -name "*.sh" -execdir bash {} \;` takes a long time and it has no verbose output which makes it impossible to know the install status.

**Comment by sjanssen2** [comment]
I had to make conda installations `--quiet` because Travis will fail due to too long log files otherwise.

**Comment by tanaes** [comment]
Can update the module installs with an `echo "installing foo"` if that helps...

**Comment by antgonza** [comment]
@sjanssen2, makes sense. @tanaes, right, that might be the easiest.
