### ISSUE TITLE
remove all conda environments

### ISSUE THREAD

**Issue by antgonza** [biocore/oecophylla#38]
is there an easy way to delete all the conda environments created by oecophylla? this might be a good feature to add so installation testing goes smoother

**Comment by tanaes** [comment]
That's a great idea 👍

Would this be best accomplished as an independent shell script or part of
the install script?

**Comment by antgonza** [comment]
yes, what about delete.sh ?

**Comment by tanaes** [comment]
Some additional thoughts on this (I don't know how relevant):

I have, in the 'utils' module, a set of 'clean' commands, which can be used
to remove the processing outputs of each of the various modules.

Would it be worth the extra effort of adding 'clean-environment' rules to
that portion of the repo?

But I'm 👍 👍 for delete.sh (uninstall.sh?) in meantime.

**Comment by antgonza** [comment]
I guess a clean command will be nice to have too but not sure, wanna add an issue for that? BTW I found that some folder were being created and not in the gitignore, like: https://github.com/biocore/oecophylla/pull/41/files so not sure if we need more ...
