### ISSUE TITLE
prefix for conda environments

### ISSUE THREAD

**Issue by antgonza** [biocore/oecophylla#39]
should all the conda environments created by oecophylla be prefixed with oecophylla for easy find/delete?

So far the names I can see are:
- [ ] shotgun-metaphlan2
- [ ] shotgun-shogun
- [ ] others??

**Comment by tanaes** [comment]
We were using shotgun- as the prefix but agree that oecophylla is better.

**Comment by antgonza** [comment]
so replace shotgun for oecophylla or make them oecophylla-shotgun?

**Comment by tanaes** [comment]
I think replace shotgun with oecophylla
