### ISSUE TITLE
Update testing to allow speedier but more limited travis testing

### ISSUE THREAD

**Issue by tanaes** [biocore/oecophylla#43]
Most of time is spent actually running the constituent tools. 

Would be more efficient to have travis do:
- testing installation
- running snakemake with the `--dry-run` option to validate snakefiles

Then could do actual testing of specific modules on system.

**Comment by antgonza** [comment]
not sure if relevant but you could also split the tests in 2 ...

**Comment by tanaes** [comment]
How do you mean?

**Comment by antgonza** [comment]
Basically in Qiita we split the tests into 3 separate travis jobs as the tests are independent to speed them up, [see here](https://github.com/biocore/qiita/blob/master/.travis.yml#L6)

**Comment by tanaes** [comment]
Still working on modularizing testing options (e.g. testing / installing one module at a time) but closing for now with PR #47
