### ISSUE TITLE
Allow for configuration file to specify multiple DBs

### ISSUE THREAD

**Issue by mortonjt** [biocore/oecophylla#60]

**Comment by tkosciolek** [comment]
depends on #67 
requires modifications to `scripts/oecophylla.py`

**Comment by tanaes** [comment]
Which type of DBs?

For filtering:
- requires using a different filter mechanism than we're currently using (bowtie2 only accepts one db)

For taxonomy tools: 
- ???

**Comment by tanaes** [comment]
Closing this for now.
