### ISSUE TITLE
Redo `install.sh` within oecophylla script

### ISSUE THREAD

**Issue by mortonjt** [biocore/oecophylla#64]
It would be great if we could move all of the contents of `install.sh` into [`oecophylla/oecophylla.py`](https://github.com/biocore/oecophylla/blob/master/scripts/oecophylla.py) as a separate subcommand

**Comment by jwdebelius** [comment]
I can look at this as I'm working through the issue with the installation

**Comment by tkosciolek** [comment]
@jwdebelius

**Comment by tanaes** [comment]
Addressed
