### ISSUE TITLE
Need to have filtering be an explicit params in Snakefile

### ISSUE THREAD

**Issue by mortonjt** [biocore/oecophylla#68]
Applying different dbs to different samples will introduce bias.

We will need to fix this in the `qc.rule` in addition to `parse.py`

**Comment by mortonjt** [comment]
All instances of [this](https://github.com/biocore/oecophylla/blob/master/oecophylla/qc/qc.rule#L57)

needs to be replaced with 

`filter_db = config['params']['filter_db']`

**Comment by tanaes** [comment]
fixed in #73
