### ISSUE TITLE
Bracken installation code not working in Travis

### ISSUE THREAD

**Issue by qiyunzhu** [biocore/oecophylla#83]
`conda install bracken` works perfectly in the local system. But it fails in Travis. Dunno why. See `taxonomy/oecophylla-kraken.yaml`.

**Comment by tanaes** [comment]
@sjanssen2 

@qiyunzhu , is there a commit you can link to where it fails so we can see error message?

**Comment by qiyunzhu** [comment]
Hi @tanaes This commit did: https://github.com/biocore/oecophylla/pull/70/commits/4878568d7c4a5e68dde5d52319c191897e8bc2ca

Travis didn't print out any error message, but simply said that taxonomy.sh failed.

**Comment by tanaes** [comment]
no longer installing environments on Travis
