### ISSUE TITLE
Translate MetaPhlAn2 taxonomy terms back to NCBI TaxIDs

### ISSUE THREAD

**Issue by qiyunzhu** [biocore/oecophylla#94]
Currently I have a work around that maps all MetaPhlAn2 terms from kingdom to species to NCBI TaxIDs. Strains can't be mapped because there is no "strain" level in NCBI. In some cases, taxa below species in NCBI were raised to species in MetaPhlAn2. What to do with them is an open question. Leaving them as is may cause inconsistency when comparing to other profilers. Merging them to higher level species / genus will reduce the resolution of MetaPhlAn2.

**Comment by tanaes** [comment]
Is this currently handled with rule in dev?

**Comment by qiyunzhu** [comment]
@tanaes Yes it is taken care of. We will need @sjanssen2 to generate that dictionary externally.

**Comment by tanaes** [comment]
resolved in #118
