### ISSUE TITLE
Re-estimate per-rank abundance based on Centrifuge result

### ISSUE THREAD

**Issue by qiyunzhu** [biocore/oecophylla#95]
Centrifuge produces reports in the same format as Kraken. Theoretically we can run Bracken on Centrifuge result to re-estimate per-rank profiles. However [Bracken](https://peerj.com/articles/cs-104/) (Bayesian Reestimation of Abundance after Classification with KrakEN) may or may not be the recommended tool for doing this. May need input from Centrifuge / Bracken authors.

**Comment by tanaes** [comment]
Fixed in #100
